// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Podkop.FindingComments.Infrastructure;

#nullable disable

namespace Podkop.FindingComments.Infrastructure.Migrations
{
    [DbContext(typeof(FindingCommentsDbContext))]
    [Migration("20260828101520_AddFindingCommentsOutbox")]
    partial class AddFindingCommentsOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finding_comments")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Podkop.FindingComments.Domain.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("finding_id");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.ToTable("comments", "finding_comments");
                });

            modelBuilder.Entity("Podkop.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "finding_comments");
                });

            modelBuilder.Entity("Podkop.FindingComments.Domain.Comment", b =>
                {
                    b.OwnsMany("Podkop.FindingComments.Domain.CommentVoteEntry", "Votes", b1 =>
                        {
                            b1.Property<Guid>("comment_id")
                                .HasColumnType("uuid")
                                .HasColumnName("comment_id");

                            b1.Property<string>("Voter")
                                .HasColumnType("text")
                                .HasColumnName("voter");

                            b1.Property<string>("VoteDirection")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("vote_direction");

                            b1.HasKey("comment_id", "Voter")
                                .HasName("pk_comment_votes");

                            b1.ToTable("comment_votes", "finding_comments");

                            b1.WithOwner()
                                .HasForeignKey("comment_id")
                                .HasConstraintName("fk_comment_votes_comments_comment_id");
                        });

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
