<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Podkop.FindingComments.Application\Podkop.FindingComments.Application.csproj" />
    <ProjectReference Include="..\Podkop.FindingComments.Contracts\Podkop.FindingComments.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Shared\Podkop.Shared.Infrastructure\Podkop.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
